version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - image-select
    restart: unless-stopped

  backend:
    image: shivamsingh6490/intern-backend:latest   # ✅ your backend image
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - image-select
    restart: unless-stopped
    volumes:
      - ./server/logs:/app/logs
    env_file:
      - ./server/.env

  frontend:
    image: shivamsingh6490/intern-frontend:latest  # ✅ should be your FRONTEND image
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - image-select
    restart: unless-stopped
    env_file:
      - ./client/.env

networks:
  image-select:
    driver: bridge
